"""
Package path and filename constants.
"""

__all__ = [
    'ASSUMPTIONS_FILENAME',
    'CLAIMS_FILENAME',
    'CODEBASE_FILENAME',
    'DATASETS_FILENAME',
    'DEFAULT_PACKAGE_DIRNAME',
    'FIGURES_FILENAME',
    'KNOWN_PACKAGE_FILENAMES',
    'MANIFEST_FILENAME',
    'METHODS_FILENAME',
    'OPERATIONS_FILENAME',
    'PAPER_FILENAME',
    'PROVENANCE_FILENAME',
    'RELATED_WORK_FILENAME',
]

DEFAULT_PACKAGE_DIRNAME = 'scp-package'

MANIFEST_FILENAME = 'manifest.yaml'
PAPER_FILENAME = 'paper.yaml'
CLAIMS_FILENAME = 'claims.yaml'
FIGURES_FILENAME = 'figures.yaml'
DATASETS_FILENAME = 'datasets.yaml'
METHODS_FILENAME = 'methods.yaml'
CODEBASE_FILENAME = 'codebase.yaml'
ASSUMPTIONS_FILENAME = 'assumptions.yaml'
RELATED_WORK_FILENAME = 'related-work.yaml'
OPERATIONS_FILENAME = 'operations.yaml'
PROVENANCE_FILENAME = 'provenance.yaml'

KNOWN_PACKAGE_FILENAMES = (
    MANIFEST_FILENAME,
    PAPER_FILENAME,
    CLAIMS_FILENAME,
    FIGURES_FILENAME,
    DATASETS_FILENAME,
    METHODS_FILENAME,
    CODEBASE_FILENAME,
    ASSUMPTIONS_FILENAME,
    RELATED_WORK_FILENAME,
    OPERATIONS_FILENAME,
    PROVENANCE_FILENAME,
)
