import { CATEGORY_COLORS, COLORS } from '../core/colors.js'
import { defineAnimationBlockConfig } from './animationBlockSchema.js'

const CONVERSION_TOOL_CONTAINER_VISIBLE_WIDTH_RATIO =
  ((13319.685 + 60.75 / 2) - (125.24 - 60.75 / 2)) / 13445

export const BLOCK1_CONFIG = defineAnimationBlockConfig({
  id: 'block1',

  stage: {
    width: 1600,
    height: 900,
    frameRate: 30,
  },

  presentation: {
    ariaLabel: 'Scientific output conversion animation',
    storyline: {
      referenceWidth: 1200,
      canvasReferenceWidth: 1240,
      stageGap: 0,
      horizontalPadding: 0,
      iconContainerSize: 50,
      textBlockWidth: 160,
      textBlockHeight: 80,
      iconTextGap: 10,
      textGap: 2,
      titleMaxFontSize: 14,
      bodyMaxFontSize: 12,
      progressBridge: {
        gap: 4,
        nodeDiameter: 18,
        edgeThickness: 2,
        inactiveColor: COLORS.border,
        inactiveOpacity: 0.18,
        activeEdgeColor: COLORS.brightCyan,
        activeOpacity: 1,
      },
      phases: [
        {
          id: 'research-process',
          phaseId: 'research',
          title: 'Research process',
          description: 'The research process produces artifacts',
          iconPath: 'icons/story/research-process.png',
          iconScale: 0.6,
          accentColor: COLORS.brightCyan,
          activateAt: { stepId: 'research-process-path', offsetMs: 200 },
        },
        {
          id: 'scientific-output',
          phaseId: 'scientificOutput',
          title: 'Scientific output',
          description: 'Reproducible scientific outputs are packed',
          iconPath: 'icons/story/scientific-output.png',
          iconScale: 0.6,
          accentColor: CATEGORY_COLORS.paper,
          activateAt: {
            stepId: 'research-process-to-scientific-output',
            offsetMs: 600,
          },
        },
        {
          id: 'conversion-tool',
          phaseId: 'conversionTool',
          title: 'Conversion tool',
          description: 'Artifacts are processed and transformed',
          iconPath: 'icons/story/conversion-tool.png',
          iconScale: 0.7,
          accentColor: CATEGORY_COLORS.code,
          activateAt: {
            stepId: 'output-to-conversion-tool',
            offsetMs: 300,
          },
        },
        {
          id: 'knowledge-graph',
          phaseId: 'knowledgeGraph',
          title: 'Knowledge graph',
          description: 'Artifacts turn into universal schemas',
          iconPath: 'icons/story/knowledge-graph.png',
          iconScale: 0.6,
          accentColor: CATEGORY_COLORS.data,
          activateAt: {
            stepId: 'conversion-tool-to-graph',
            offsetMs: 700,
          },
        },
      ],
    },
  },

  sequence: {
    reducedMotionStepId: 'graph-edges-appear',
    steps: [
      {
        id: 'researcher-appears',
        ownerPhaseId: 'research',
        kind: 'phase',
        durationMs: 100,
        caption: 'A researcher produces paper, code, and dataset outputs.',
        cues: {},
        overlays: { conversionTool: { visible: false, intro: false, spinning: false } },
      },
      {
        id: 'research-process-path',
        ownerPhaseId: 'research',
        kind: 'phase',
        durationMs: 2000,
        caption: 'The research process unfolds as connected steps under the researcher.',
        cues: {},
        overlays: { conversionTool: { visible: false, intro: false, spinning: false } },
      },
      {
        id: 'research-process-to-scientific-output',
        ownerPhaseId: 'scientificOutput',
        kind: 'transition',
        durationMs: 2400,
        caption: 'Paper, code, and data become grouped scientific output.',
        cues: {},
        overlays: { conversionTool: { visible: false, intro: false, spinning: false } },
      },
      {
        id: 'scientific-output-idle',
        ownerPhaseId: 'scientificOutput',
        kind: 'phase',
        durationMs: 100,
        caption: 'The grouped scientific output waits for conversion.',
        cues: {
          conversionToolShell: { leadInMs: 100, revealDurationMs: 100 },
        },
        overlays: { conversionTool: { visible: true, intro: true, spinning: false } },
      },
      {
        id: 'output-to-conversion-tool',
        ownerPhaseId: 'conversionTool',
        kind: 'transition',
        durationMs: 2000,
        caption: 'Copies enter the conversion tool for structured processing.',
        cues: {
          conversionToolInputs: { delayMs: 200, revealDurationMs: 350 },
        },
        overlays: { conversionTool: { visible: true, intro: false, spinning: false } },
      },
      {
        id: 'conversion-tool-processing',
        ownerPhaseId: 'conversionTool',
        kind: 'phase',
        durationMs: 2000,
        caption: 'The conversion tool processes each artifact into graph-ready data.',
        cues: {},
        overlays: { conversionTool: { visible: true, intro: false, spinning: true } },
      },
      {
        id: 'conversion-tool-to-graph',
        ownerPhaseId: 'knowledgeGraph',
        kind: 'transition',
        durationMs: 2000,
        caption: 'The tool converts scientific outputs into category-aware graph nodes.',
        cues: {},
        overlays: { conversionTool: { visible: true, intro: false, spinning: false } },
      },
      {
        id: 'graph-edges-appear',
        ownerPhaseId: 'knowledgeGraph',
        kind: 'phase',
        durationMs: 2000,
        caption: 'Sparse relationships connect paper, code, and data into a knowledge graph.',
        cues: {},
        overlays: { conversionTool: { visible: true, intro: false, spinning: false } },
      },
    ],
  },

  theme: {
    categories: CATEGORY_COLORS,
    colors: {
      background: COLORS.background,
      ink: COLORS.ink,
      muted: COLORS.muted,
      edge: COLORS.edge,
      brightCyan: COLORS.brightCyan,
    },
    effects: {
      glow: {
        layers: [
          { width: 12, opacity: 12 },
          { width: 6, opacity: 26 },
        ],
      },
    },
  },

  assets: {
    researcher: {
      lottieId: 'researcher',
      path: 'characters/researcher.png',
      intrinsicSize: [1254, 1254],
    },
    outputPaper: {
      lottieId: 'scientific-output-paper',
      path: 'objects/so_paper.svg',
      intrinsicSize: [512, 512],
    },
    outputCode: {
      lottieId: 'scientific-output-code',
      path: 'objects/so_code.svg',
      intrinsicSize: [512, 512],
    },
    outputData: {
      lottieId: 'scientific-output-data',
      path: 'objects/so_dataset.svg',
      intrinsicSize: [512, 512],
    },
    graphCode: { lottieId: 'graph-icon-code', path: 'icons/code.svg', intrinsicSize: [800, 800] },
    graphFigure: { lottieId: 'graph-icon-figure', path: 'icons/figure.svg', intrinsicSize: [512, 512] },
    graphFolder: { lottieId: 'graph-icon-folder', path: 'icons/folder.svg', intrinsicSize: [512, 512] },
    graphIdea: { lottieId: 'graph-icon-idea', path: 'icons/idea.svg', intrinsicSize: [512, 512] },
    graphJson: { lottieId: 'graph-icon-json', path: 'icons/json.svg', intrinsicSize: [800, 800] },
    graphMethod: { lottieId: 'graph-icon-method', path: 'icons/method.svg', intrinsicSize: [512, 512] },
    graphTree: { lottieId: 'graph-icon-tree', path: 'icons/tree.svg', intrinsicSize: [800, 800] },
    graphYaml: { lottieId: 'graph-icon-yaml', path: 'icons/yaml.svg', intrinsicSize: [512, 512] },
    conversionToolContainer: {
      path: 'objects/conversion_tool_container.svg',
      intrinsicSize: [13445, 8932],
      visibleWidthRatio: CONVERSION_TOOL_CONTAINER_VISIBLE_WIDTH_RATIO,
    },
    conversionToolEngine: {
      path: 'objects/conversion_tool_engine.svg',
      intrinsicSize: [4247, 4247],
    },
  },

  phases: {
    research: {
      anchor: [300, 170],
      researcher: {
        assetId: 'researcher',
        displayWidth: 250,
        positionOffset: [0, 0],
      },
      entrance: {
        startScalePercent: 72,
        scaleDurationFrames: 20,
        opacityDurationFrames: 15,
      },
      scatteredOutputOffsets: {
        paper: [-165, 20],
        code: [165, -55],
        data: [175, 135],
      },
      process: {
        title: {
          text: 'Research process',
          color: COLORS.brightCyan,
          fontSize: 24,
          positionOffset: [0, 90],
        },
        pathOffset: [0, 145],
        nodeGap: 60,
        outputIconSize: 70,
        emptyNode: {
          radius: 12,
          strokeWidth: 2,
          strokeColor: COLORS.muted,
          fillColor: COLORS.background,
        },
        edge: { thickness: 5, opacity: 52, color: COLORS.muted },
        nodes: [
          { index: 1, type: 'empty' },
          { index: 2, type: 'icon', category: 'data', assetId: 'outputData' },
          { index: 3, type: 'empty' },
          { index: 4, type: 'empty' },
          { index: 5, type: 'icon', category: 'code', assetId: 'outputCode' },
          { index: 6, type: 'empty' },
          { index: 7, type: 'icon', category: 'paper', assetId: 'outputPaper' },
        ],
        animation: {
          nodeRevealFrameGap: 8,
          nodeRevealDurationFrames: 6,
          edgeDrawDurationFrames: 8,
        },
        knockout: {
          size: [342, 85],
          positionOffset: [0, 125],
          cornerRadius: 12,
          fillColor: COLORS.background,
        },
      },
    },

    scientificOutput: {
      anchor: [300, 460],
      categories: {
        paper: { assetId: 'outputPaper' },
        code: { assetId: 'outputCode' },
        data: { assetId: 'outputData' },
      },
      row: {
        centerOffset: [0, -10],
        yOffset: 15,
        categoryXOffsets: { paper: -130, code: 0, data: 130 },
      },
      artifact: {
        tileSize: 85,
        iconSize: 95,
        cornerRadius: 14,
        borderWidth: 2,
        label: {
          fontSize: 16,
          knockoutSize: [50, 25],
          knockoutOffset: [0, 43],
          knockoutCornerRadius: 3,
          textBoxSize: [50, 21],
          textOffset: [0, 48],
        },
      },
      copy: { tileSize: 60, iconSize: 68, cornerRadius: 10 },
      panel: {
        size: [300, 160],
        positionOffset: [0, 0],
        cornerRadius: 22,
        borderWidth: 2,
        strokeGradient: [
          { offset: 0, color: '#7df9ff' },
          { offset: 0.55, color: '#a782ff' },
          { offset: 1, color: '#43ffb5' },
        ],
        title: {
          text: 'Scientific output',
          topInset: 10,
          color: COLORS.brightCyan,
          fontWeight: 600,
          fontSize: 24,
        },
      },
      animation: {
        defaultStartStaggerFrames: 4,
        animateInStartFrame: 14,
        animateInStaggerFrames: 10,
        moveEndFrame: 44,
        moveEndPaddingFrames: 2,
        popStartScalePercent: 15,
        popDurationFrames: 12,
        opacityDurationFrames: 8,
        consumeFadeDurationFrames: 16,
        tileRevealDurationFrames: 8,
        panelRevealStartFrame: 32,
        panelRevealEndFrame: 50,
      },
    },

    conversionTool: {
      anchor: [300, 745],
      containerAsset: { assetId: 'conversionToolContainer' },
      engineAsset: { assetId: 'conversionToolEngine' },
      panel: { width: 470, height: 312 },
      layout: {
        launchOffset: [270, 0],
        inputEngineGap: 159,
        connectorHubInset: 10,
      },
      title: {
        text: 'Conversion tool',
        topInset: 28,
        color: COLORS.brightCyan,
        fontWeight: 600,
        fontSize: 28,
      },
      inputs: {
        width: 82,
        height: 40,
        cornerRadius: 16,
        labelYOffset: 12,
        verticalGap: 25,
        labelFontSize: 19,
        portRadius: 7,
        borderWidth: 3,
      },
      engine: { size: 150 },
      connectors: {
        thickness: 4,
        opacity: 65,
        drawDurationFrames: 14,
        flowDash: 14,
        flowGap: 18,
        flowOffset: -64,
        flowPulseCount: 4,
        flowPulseStagger: 9,
        flowPulseWidth: 30,
        flowThickness: 9,
      },
      process: {
        fontSize: 14,
        gap: 10,
        yOffset: 105,
        inactiveColor: COLORS.muted,
        activeColor: COLORS.brightCyan,
        inactiveFontWeight: 400,
        activeFontWeight: 800,
        logColor: COLORS.ink,
        items: [
          { type: 'status', key: 'parse', text: 'Parse', activationFrame: 8 },
          { type: 'arrow', key: 'parse-normalize', text: '→', activationFrame: 20 },
          { type: 'status', key: 'normalize', text: 'Normalize', activationFrame: 26 },
          { type: 'arrow', key: 'normalize-validate', text: '→', activationFrame: 38 },
          { type: 'status', key: 'validate', text: 'Validate', activationFrame: 44 },
        ],
      },
      animation: {
        outputArrivalProgress: 0.67,
        outputArrivalStaggerFrames: 5,
        minimumOutputArrivalFrame: 18,
        outputArrivalEndPaddingFrames: 8,
      },
    },

    knowledgeGraph: {
      anchor: [1100, 540],
      fieldOffsets: { left: -375, right: 375, top: -370, bottom: 360 },
      clusterCenterOffsets: {
        paper: [0, -230],
        code: [230, 190],
        data: [-230, 190],
      },
      clusters: {
        paper: { ringRadius: 175, ringStartAngleDegrees: -90 },
        code: { ringRadius: 135, ringStartAngleDegrees: -45 },
        data: { ringRadius: 135, ringStartAngleDegrees: -45 },
      },
      content: {
        paper: [
          { title: 'Claim', icon: 'idea', assetId: 'graphIdea', role: 'ring' },
          { title: 'Claim', icon: 'idea', assetId: 'graphIdea', role: 'ring' },
          { title: 'Figure', icon: 'figure', assetId: 'graphFigure', role: 'ring' },
          { title: 'Figure', icon: 'figure', assetId: 'graphFigure', role: 'ring' },
          { title: 'Method', icon: 'method', assetId: 'graphMethod', role: 'ring' },
          { title: 'Method', icon: 'method', assetId: 'graphMethod', role: 'ring' },
          { title: 'Method', icon: 'method', assetId: 'graphMethod', role: 'ring' },
        ],
        code: [
          { title: 'Struct', icon: 'tree', assetId: 'graphTree', role: 'central' },
          { title: 'Script', icon: 'code', assetId: 'graphCode', role: 'ring' },
          { title: 'Script', icon: 'code', assetId: 'graphCode', role: 'ring' },
          { title: 'Script', icon: 'code', assetId: 'graphCode', role: 'ring' },
          { title: 'Config', icon: 'yaml', assetId: 'graphYaml', role: 'ring' },
        ],
        data: [
          { title: 'Struct', icon: 'tree', assetId: 'graphTree', role: 'central' },
          { title: 'Data', icon: 'folder', assetId: 'graphFolder', role: 'ring' },
          { title: 'Data', icon: 'folder', assetId: 'graphFolder', role: 'ring' },
          { title: 'Data', icon: 'folder', assetId: 'graphFolder', role: 'ring' },
          { title: 'Meta', icon: 'json', assetId: 'graphJson', role: 'ring' },
        ],
      },
      generation: {
        minimumConnectionsPerClusterPair: 4,
        paperExtraEdgeProbability: 0.25,
        neighborEdgeProbability: 0.5,
        minimumEdgeWeight: 0.2,
        edgeWeightSeed: 'block-1-edge-weights-v1',
        paperTreeSeed: 'block-1-paper-spanning-tree-v2',
        paperTreeLinksSeed: 'block-1-paper-spanning-tree-links-v2',
        paperExtrasSeed: 'block-1-paper-extras-v2',
        codeNeighborsSeed: 'block-1-code-neighbors-v2',
        dataNeighborsSeed: 'block-1-data-neighbors-v2',
        clusterConnectionsSeed: 'block-1-cluster-connections-v1',
      },
      node: {
        diameter: 90,
        iconSize: 100,
        borderWidth: 2,
        bodyColor: COLORS.background,
        alpha: 1,
        title: {
          fontSize: 16,
          fontWeight: 600,
          knockoutSize: [64, 16],
          knockoutOffset: [0, 38],
          knockoutCornerRadius: 3,
          textBoxSize: [72, 18],
          textOffset: [0, 40],
        },
      },
      edge: { maximumThickness: 10, opacity: 38 },
      animation: {
        nodeStartFrame: 8,
        nodeStaggerFrames: 2,
        nodeTravelDurationFrames: 34,
        nodeStartScalePercent: 35,
        nodeOpacityDurationFrames: 5,
        edgeDrawDurationFrames: 14,
      },
    },
  },

  constraints: {
    synchronizedPanelWidth: {
      sourcePhaseId: 'conversionTool',
      targetPhaseIds: ['scientificOutput', 'conversionTool'],
    },
  },
})
