import { CATEGORY_COLORS, COLORS } from '../core/colors.js'
import { defineAnimationBlockConfig } from './animationBlockSchema.js'

export const BLOCK2_CONFIG = defineAnimationBlockConfig({
  id: 'block2',

  stage: {
    width: 1600,
    height: 900,
    frameRate: 30,
  },

  presentation: {
    ariaLabel: 'User, LLM Agent, and MCP animation',
    storylineAriaLabel: 'Block 2 storyline',
    storyline: {
      referenceWidth: 1200,
      canvasReferenceWidth: 1240,
      stageGap: 0,
      horizontalPadding: 0,
      iconContainerSize: 50,
      textBlockWidth: 160,
      textBlockHeight: 80,
      iconTextGap: 10,
      textGap: 2,
      titleMaxFontSize: 14,
      bodyMaxFontSize: 12,
      progressBridge: {
        gap: 4,
        nodeDiameter: 18,
        edgeThickness: 2,
        inactiveColor: COLORS.border,
        inactiveOpacity: 0.18,
        activeEdgeColor: COLORS.brightCyan,
        activeOpacity: 1,
      },
      phases: [
        {
          id: 'user-connection',
          phaseId: 'userConnection',
          title: 'User connection',
          description: 'User connects to the LLM agent to use SCP',
          iconPath: 'icons/story/user-connection.png',
          iconScale: 0.6,
          accentColor: COLORS.brightCyan,
          activateAt: { stepId: 'user-agent-connect', offsetMs: 0 },
        },
        {
          id: 'user-query',
          phaseId: 'userQuery',
          title: 'LLM agent queries',
          description: 'The user makes different queries to the LLM agent',
          iconPath: 'icons/story/queries.png',
          iconScale: 0.6,
          accentColor: CATEGORY_COLORS.paper,
          activateAt: { stepId: 'query-enters', offsetMs: 0 },
        },
        {
          id: 'mcp-interaction',
          phaseId: 'mcpInteraction',
          title: 'MCP interaction',
          description: 'The LLM agent interacts with MCP',
          iconPath: 'icons/story/mcp-interaction.png',
          iconScale: 0.7,
          accentColor: CATEGORY_COLORS.code,
          activateAt: { stepId: 'mcp-table-connects', offsetMs: 0 },
        },
        {
          id: 'graph-access',
          phaseId: 'graphAccess',
          title: 'Graph access',
          description: 'MCP tools extract information from the graph',
          iconPath: 'icons/story/graph-access.png',
          iconScale: 0.6,
          accentColor: CATEGORY_COLORS.data,
          activateAt: { stepId: 'graph-access-activations', offsetMs: 0 },
        },
      ],
    },
  },

  sequence: {
    reducedMotionStepId: 'graph-access-idle',
    steps: [
      {
        id: 'compress-knowledge-graph',
        ownerPhaseId: 'graphAccess',
        kind: 'transition',
        durationMs: 1800,
        caption: 'The knowledge graph compresses into a compact persistent graph.',
        cues: {},
        overlays: {},
      },
      {
        id: 'user-agent-connect',
        ownerPhaseId: 'userConnection',
        kind: 'phase',
        durationMs: 1600,
        caption: 'The user connects to the LLM agent.',
        cues: {},
        overlays: {},
      },
      {
        id: 'query-enters',
        ownerPhaseId: 'userQuery',
        kind: 'phase',
        durationMs: 3900,
        caption: 'The user sends a structured query to the LLM agent.',
        cues: {},
        overlays: {},
      },
      {
        id: 'mcp-table-connects',
        ownerPhaseId: 'mcpInteraction',
        kind: 'phase',
        durationMs: 2800,
        caption: 'The LLM agent calls the read-only SCP MCP tools.',
        cues: {},
        overlays: {},
      },
      {
        id: 'graph-access-activations',
        ownerPhaseId: 'graphAccess',
        kind: 'phase',
        durationMs: 5400,
        caption: 'Each MCP tool activates its relevant compact graph context.',
        cues: {},
        overlays: {},
      },
      {
        id: 'graph-access-idle',
        ownerPhaseId: 'graphAccess',
        kind: 'phase',
        durationMs: 100,
        caption: 'The graph, MCP table, and agent connections return to idle.',
        cues: {},
        overlays: {},
      },
    ],
  },

  theme: {
    categories: CATEGORY_COLORS,
    toolFamilies: {
      assumption: CATEGORY_COLORS.paper,
      claim: CATEGORY_COLORS.paper,
      codeArtifact: CATEGORY_COLORS.code,
      dataset: CATEGORY_COLORS.data,
      methodStep: CATEGORY_COLORS.code,
      mixed: COLORS.ink,
      study: COLORS.ink,
    },
    colors: {
      background: COLORS.background,
      panel: COLORS.panel,
      ink: COLORS.ink,
      muted: COLORS.muted,
      border: COLORS.border,
      edge: COLORS.edge,
      brightCyan: COLORS.brightCyan,
      white: COLORS.white,
    },
    effects: {
      glow: {
        layers: [
          { width: 12, opacity: 12 },
          { width: 6, opacity: 26 },
        ],
      },
    },
  },

  assets: {
    user: {
      lottieId: 'block2-user',
      path: 'characters/user.png',
      intrinsicSize: [1381, 1139],
    },
    agent: {
      lottieId: 'block2-agent',
      path: 'characters/agent.png',
      intrinsicSize: [1000, 1000],
    },
  },

  phases: {
    userConnection: {
      anchor: [180, 150],
      user: {
        icon: {
          assetId: 'user',
          positionOffset: [0, 0],
          displayWidth: 250,
        },
        title: {
          text: 'User',
          zOrder: 'frontmost',
          positionOffset: [0, 85],
          fontSize: 24,
          color: COLORS.brightCyan,
          textBoxSize: [100, 20],
          knockout: {
            size: [80, 34],
            cornerRadius: 12,
            fillColor: COLORS.background,
          },
        },
      },
      agent: {
        icon: {
          assetId: 'agent',
          positionOffset: [300, 280],
          displayWidth: 170,
        },
        title: {
          text: 'LLM agent',
          zOrder: 'frontmost',
          positionOffset: [300, 355],
          fontSize: 24,
          color: COLORS.brightCyan,
          textBoxSize: [180, 30],
          knockout: {
            size: [140, 40],
            cornerRadius: 6,
            fillColor: COLORS.background,
          },
        },
      },
      edge: {
        color: COLORS.brightCyan,
        thickness: 2,
        opacity: 120,
        fromHandleOffset: [200, 0],
        toHandleOffset: [0, -200],
      },
      animation: {
        revealDurationMs: 200,
        agentDelayMs: 350,
        edgeDelayMs: 600,
        edgeDrawDurationMs: 650,
        startScalePercent: 76,
      },
    },

    userQuery: {
      anchor: [180, 670],
      panel: {
        positionOffset: [0, 0],
        size: [340, 345],
        cornerRadius: 16,
        fillColor: COLORS.background,
        fillOpacity: 1,
        borderColor: COLORS.background,
        borderWidth: 8,
        borderOpacity: 0,
        title: {
          text: 'Query',
          positionOffset: [0, -165],
          align: 'center',
          fontSize: 24,
          color: COLORS.brightCyan,
          textBoxSize: [200, 30],
        },
      },
      boxes: {
        size: [320, 90],
        groupPositionOffset: [0, 20],
        cornerRadius: 14,
        gap: 14,
        fillOpacity: 0.12,
        borderWidth: 2,
        borderOpacity: 72,
        text: {
          positionOffset: [-138, -24],
          align: 'left',
          fontSize: 14,
          color: COLORS.ink,
          textBoxSize: [280, 76],
        },
        items: [
          {
            category: 'paper',
            text: 'Where is the description of the method used to produce the panel A in Figure 1?',
          },
          {
            category: 'code',
            text: 'Locate the code corresponding to the preprocessing described in Algorithm S1.',
          },
          {
            category: 'data',
            text: 'Which data should I download to reproduce results in Section 2.1?',
          },
        ],
      },
      edge: {
        color: COLORS.brightCyan,
        thickness: 4,
        opacity: 82,
        mirrorUserAgentCurve: true,
      },
      userToQueryEdge: {
        color: COLORS.brightCyan,
        thickness: 2,
        opacity: 82,
        animation: {
          drawDurationMs: 2200,
        },
      },
      animation: {
        panelDelayMs: 0,
        panelRevealDurationMs: 350,
        contentStartDelayMs: 400,
        boxStaggerMs: 450,
        boxRevealDurationMs: 650,
        slideDistance: 70,
        charactersPerSecond: 28,
        edgeDrawDurationMs: 650,
      },
    },

    mcpInteraction: {
      anchor: [1000, 450],
      table: {
        size: [580, 700],
        cornerRadius: 8,
        borderWidth: 2,
        headerHeight: 40,
        header: {
          fillColor: COLORS.muted,
          fillOpacity: 0.08,
        },
        footerTitle: {
          text: 'Model Context Protocol',
          gap: 4,
          fontSize: 24,
          color: COLORS.brightCyan,
          align: 'center',
          textBoxSize: [580, 32],
        },
        columns: {
          api: {
            widthPercent: (280 / 580) * 100,
            header: {
              text: 'Tool',
              align: 'center',
              verticalAlign: 'center',
              padding: [8, 12, 0, 12],
              fontSize: 19,
              lineHeight: 22.8,
              characterWidthRatio: 0.6,
            },
            cells: {
              align: 'left',
              verticalAlign: 'center',
              padding: [8, 18, 8, 18],
              fontSize: 16,
              lineHeight: 16.8,
              characterWidthRatio: 0.6,
            },
          },
          description: {
            header: {
              text: 'Description',
              align: 'center',
              verticalAlign: 'center',
              padding: [8, 12, 0, 12],
              fontSize: 19,
              lineHeight: 22.8,
              characterWidthRatio: 0.6,
            },
            cells: {
              align: 'left',
              verticalAlign: 'center',
              padding: [8, 18, 8, 18],
              fontSize: 14,
              lineHeight: 16.8,
              characterWidthRatio: 0.7,
            },
          },
        },
        rows: [
          {
            category: 'paper',
            api: 'get_study_summary',
            description: 'Returns the study manifest and package overview',
            toolFamily: 'study',
          },
          {
            category: 'paper',
            api: 'list_claims',
            description: 'Lists claims, optionally filtered by \n section or evidence status',
            toolFamily: 'claim',
          },
          {
            category: 'paper',
            api: 'trace_claim_to_evidence',
            description: 'Returns a claim plus the linked \n evidence objects behind it',
            toolFamily: 'mixed',
          },
          {
            category: 'paper',
            api: 'get_figure_provenance',
            description: 'Returns a figure plus linked \n data, code, and method steps',
            toolFamily: 'mixed',
          },
          {
            category: 'data',
            api: 'get_dataset_description',
            description: 'Returns a dataset description \n and optional usage notes',
            toolFamily: 'dataset',
          },
          {
            category: 'paper',
            api: 'get_preprocessing_chain',
            description: 'Returns method-step objects for a \n method, claim, or figure',
            toolFamily: 'methodStep',
          },
          {
            category: 'code',
            api: 'explain_code_file',
            description: 'Returns a code artifact by ID \n or package path',
            toolFamily: 'codeArtifact',
          },
          {
            category: 'paper',
            api: 'list_assumptions',
            description: 'Lists assumptions, caveats, and \n limitations by object or severity',
            toolFamily: 'assumption',
          },
          {
            category: 'paper',
            api: 'find_related_objects',
            description: 'Returns neighboring objects and \n provenance links for an object',
            toolFamily: 'mixed',
          },
        ],
      },
      animation: {
        tableRevealDurationMs: 500,
        arrowStartDelayMs: 400,
      },
      arrows: {
        color: COLORS.brightCyan,
        thickness: 2,
        opacity: 80,
        endpointSphereDiameter: 14,
        durationSeed: 'block-2-mcp-row-arrow-durations-v1',
        minimumDurationMs: 400,
        maximumDurationMs: 1200,
      },
    },

    graphAccess: {
      anchor: [1450, 450],
      compactGraph: {
        anchor: [1450, 450],
        nodesPerCategory: 3,
        clusterCenterOffsets: {
          paper: [0, -55],
          code: [-65, 60],
          data: [65, 60],
        },
        nodeRingRadius: 38,
        nodeDiameter: 26,
        nodeBorderWidth: 3,
        edgeThickness: 1.5,
        edgeOpacity: 28,
      },
      activation: {
        rowDurationMs: 600,
        selectionSeed: 'block-2-graph-access-row-selection-v1',
        rowHighlightOpacity: 18,
        inactiveArrowColor: COLORS.edge,
        inactiveGraph: {
          color: COLORS.border,
          edgeOpacity: 22,
        },
        activeNode: {
          fillBackgroundMix: 0.55,
          glowLayers: [
            { width: 16, opacity: 30 },
            { width: 9, opacity: 55 },
          ],
        },
        activeEdge: {
          color: COLORS.white,
          thickness: 6,
          opacity: 100,
          glowLayers: [
            { width: 16, opacity: 18 },
            { width: 10, opacity: 40 },
          ],
        },
        rows: [
          { paper: 2 },
          { paper: 3 },
          { paper: 2, data: 1 },
          { paper: 1, code: 1, data: 1 },
          { data: 3 },
          { paper: 2 },
          { code: 3 },
          { paper: 2 },
          { paper: 1, code: 1, data: 1 },
        ],
      },
      animation: {
        oldContentFadeStartFrame: 0,
        oldContentFadeEndFrame: 12,
        nodeMoveStartFrame: 6,
        nodeMoveEndFrame: 39,
        completeEdgeStartFrame: 33,
        completeEdgeEndFrame: 51,
      },
    },
  },

  constraints: {},
})
